### ISSUE TITLE
failed to build

### ISSUE THREAD

**Issue by jonasled2** [thcolin/epyd.js#4]
**The Error message i get is:**

_ERROR in ./resources/illustration-happy.svg
Module build failed: ReferenceError: Unknown plugin "syntax-jsx" specified in "base" at 0, attempted to resolve relative to "/root/nipper-1.0.4"
    at /root/nipper-1.0.4/node_modules/react-svg-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:177:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/root/nipper-1.0.4/node_modules/react-svg-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:153:20)
    at OptionManager.mergeOptions (/root/nipper-1.0.4/node_modules/react-svg-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:245:36)
    at OptionManager.init (/root/nipper-1.0.4/node_modules/react-svg-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:383:12)
    at File.initOptions (/root/nipper-1.0.4/node_modules/react-svg-loader/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/root/nipper-1.0.4/node_modules/react-svg-loader/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/root/nipper-1.0.4/node_modules/react-svg-loader/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at /root/nipper-1.0.4/node_modules/react-svg-loader/lib/loader.js:71:37
    at <anonymous>
 @ ./src/components/App/Web/Content/Placeholder/index.js 13:0-53
 @ ./src/containers/PlaceholderHideable.js
 @ ./src/components/App/Web/Content/index.js
 @ ./src/components/App/Web/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js

ERROR in ./resources/illustration-sad.svg
Module build failed: ReferenceError: Unknown plugin "syntax-jsx" specified in "base" at 0, attempted to resolve relative to "/root/nipper-1.0.4"
    at /root/nipper-1.0.4/node_modules/react-svg-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:177:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/root/nipper-1.0.4/node_modules/react-svg-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:153:20)
    at OptionManager.mergeOptions (/root/nipper-1.0.4/node_modules/react-svg-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:245:36)
    at OptionManager.init (/root/nipper-1.0.4/node_modules/react-svg-loader/node_modules/babel-core/lib/transformation/file/options/option-manager.js:383:12)
    at File.initOptions (/root/nipper-1.0.4/node_modules/react-svg-loader/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/root/nipper-1.0.4/node_modules/react-svg-loader/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/root/nipper-1.0.4/node_modules/react-svg-loader/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at /root/nipper-1.0.4/node_modules/react-svg-loader/lib/loader.js:71:37
    at <anonymous>
 @ ./src/components/App/Web/Content/Placeholder/index.js 14:0-49
 @ ./src/containers/PlaceholderHideable.js
 @ ./src/components/App/Web/Content/index.js
 @ ./src/components/App/Web/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js

ERROR in ./src/components/App/Web/Landing/Form/index.js
Module not found: Error: Can't resolve 'config' in '/root/nipper-1.0.4/src/components/App/Web/Landing/Form'
 @ ./src/components/App/Web/Landing/Form/index.js 13:0-28
 @ ./src/containers/FormAnalyst.js
 @ ./src/components/App/Web/Landing/index.js
 @ ./src/components/App/Web/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js

ERROR in ./src/ducks/context.js
Module not found: Error: Can't resolve 'config' in '/root/nipper-1.0.4/src/ducks'
 @ ./src/ducks/context.js 8:0-28
 @ ./src/ducks/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js_

**Comment by thcolin** [comment]
First, copy `src/config.default.js` to `src/config.js` and edit `apiKey` value with a [Google registered application api key](https://developers.google.com/youtube/registering_an_application), then retry.

**Comment by jonasled2** [comment]
it works
